import {
  getAccountCategories,
  getAccounts,
  getAccountTree,
  getAccountById,
  createAccount,
  updateAccount,
  deleteAccount,
  getAccountsByType,
  getCoaStats,
  getJournalEntries,
  getJournalEntryById,
  createJournalEntry,
  updateJournalEntry,
  postJournalEntry,
  voidJournalEntry,
  submitJournalForApproval,
  approveJournalEntry,
  rejectJournalEntry,
  getJournalChangeHistory,
  getAccountingPeriods,
  createAccountingPeriod,
  closePeriod,
  reopenPeriod,
  lockPeriod,
  getRecurringTemplates,
  createRecurringTemplate,
  deleteRecurringTemplate,
  toggleRecurringTemplate,
  executeRecurringJournals,
  backfillJournals,
  seedDefaultCOA,
} from "@/server/actions/accounting";

import {
  getGeneralLedger,
  getTrialBalance,
  getIncomeStatement,
  getBalanceSheet,
  getCashFlow,
  getAccountingDashboard,
  getTaxSummaryReport,
  getEFakturExport,
  getAgingReport,
  getDrillDownEntries,
  getPeriodClosingChecklist,
  createClosingEntries,
} from "@/server/actions/accounting-reports";

export const accountingService = {
  // COA
  getAccountCategories,
  getAccounts,
  getAccountTree,
  getAccountById,
  createAccount,
  updateAccount,
  deleteAccount,
  getAccountsByType,
  getCoaStats,
  // Journals
  getJournalEntries,
  getJournalEntryById,
  createJournalEntry,
  updateJournalEntry,
  postJournalEntry,
  voidJournalEntry,
  submitJournalForApproval,
  approveJournalEntry,
  rejectJournalEntry,
  getJournalChangeHistory,
  // Reports
  getGeneralLedger,
  getTrialBalance,
  getIncomeStatement,
  getBalanceSheet,
  getCashFlow,
  getAccountingDashboard,
  getTaxSummaryReport,
  getEFakturExport,
  getAgingReport,
  getDrillDownEntries,
  // Periods
  getAccountingPeriods,
  createAccountingPeriod,
  closePeriod,
  reopenPeriod,
  lockPeriod,
  getPeriodClosingChecklist,
  createClosingEntries,
  // Recurring
  getRecurringTemplates,
  createRecurringTemplate,
  deleteRecurringTemplate,
  toggleRecurringTemplate,
  executeRecurringJournals,
  // Utilities
  backfillJournals,
  seedDefaultCOA,
};
